# Generated by Django 3.0.6 on 2020-05-24 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, height_field='height_field', max_length=256, null=True, upload_to='pictures/%Y/%m/%D/', width_field='width_field'),
        ),
    ]
