# Generated by Django 3.0.6 on 2020-06-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
