# Generated by Django 3.0.6 on 2020-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, height_field='height_field', max_length=256, null=True, upload_to='media/pictures/%Y/%m/%D/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
