# Generated by Django 3.0.6 on 2020-06-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('post', '0012_comment_parent'),
        ('account', '0012_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
